services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: guestReservation_development
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - ".:/guestReservation"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: admin123

  test:
    build: .
    command: bundle exec rspec
    volumes:
      - ".:/guestReservation"
    depends_on:
      - db
